In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv("CKD.csv")
dataset =pd.DataFrame(dataset)
dataset = pd.get_dummies(dataset,dtype=int,drop_first='True')
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [40]:
indep = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal', 'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
print(indep)
dep = dataset[['classification_yes']]
dep

           age         bp  al  su         bgr          bu        sc  \
0     2.000000  76.459948   3   0  148.112676   57.482105  3.077356   
1     3.000000  76.459948   2   0  148.112676   22.000000  0.700000   
2     4.000000  76.459948   1   0   99.000000   23.000000  0.600000   
3     5.000000  76.459948   1   0  148.112676   16.000000  0.700000   
4     5.000000  50.000000   0   0  148.112676   25.000000  0.600000   
..         ...        ...  ..  ..         ...         ...       ...   
394  51.492308  70.000000   0   0  219.000000   36.000000  1.300000   
395  51.492308  70.000000   0   2  220.000000   68.000000  2.800000   
396  51.492308  70.000000   3   0  110.000000  115.000000  6.000000   
397  51.492308  90.000000   0   0  207.000000   80.000000  6.800000   
398  51.492308  80.000000   0   0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0  

,classification_yes
0,1
1,1
2,1
3,1
4,1
...,...
394,1
395,1
396,1
397,1


In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(indep,dep, test_size = .30, random_state = 0)

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid = {'solver':['newton_cg', 'lbfgs','liblinear','saga'],'penalty':['l2']}
grid =GridSearchCV(LogisticRegression(),param_grid,refit = True,verbose =3,n_jobs=-1,scoring ='f1_weighted')
grid.fit(X_train,Y_train)
re = grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,grid_predictions)
from sklearn.metrics import f1_score
f1_macro =f1_score(Y_test,grid_predictions,average = 'weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)
print("The confusion matrix:\n",cm)
print(clf_report)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
The f1_macro value for best parameter{'penalty': 'l2', 'solver': 'lbfgs'}: 0.9916844900066377
The confusion matrix:
 [[45  0]
 [ 1 74]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
5 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~

In [34]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid = {'kernel':['linear', 'rbf','poly','sigmoid'],'gamma':['auto','scale'],'C':[1000,100,10]}
grid =GridSearchCV(SVC(probability = True),param_grid,refit = True,verbose =3,n_jobs=-1,scoring ='f1_weighted')
grid.fit(X_train,Y_train)
re = grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,grid_predictions)
from sklearn.metrics import f1_score
f1_macro =f1_score(Y_test,grid_predictions,average = 'weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)
print("The confusion matrix:\n",cm)
print(clf_report)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
The f1_macro value for best parameter{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9834018801410106
The confusion matrix:
 [[45  0]
 [ 2 73]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120



C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini', 'entropy'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid =GridSearchCV(DecisionTreeClassifier(),param_grid,refit = True,verbose =3,n_jobs=-1,scoring ='f1_weighted')
grid.fit(X_train,Y_train)
re = grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,grid_predictions)
from sklearn.metrics import f1_score
f1_macro =f1_score(Y_test,grid_predictions,average = 'weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)
print("The confusion matrix:\n",cm)
print(clf_report)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
The f1_macro value for best parameter{'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9668037602820213
The confusion matrix:
 [[44  1]
 [ 3 72]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96        45
           1       0.99      0.96      0.97        75

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.96       120
weighted avg       0.97      0.97      0.97       120



C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini', 'entropy'],'max_features':['auto','sqrt','log2'],'n_estimators':[10, 100]}
grid =GridSearchCV(RandomForestClassifier(),param_grid,refit = True,verbose =3,n_jobs=-1,scoring ='f1_weighted')
grid.fit(X_train,Y_train)
re = grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,grid_predictions)
from sklearn.metrics import f1_score
f1_macro =f1_score(Y_test,grid_predictions,average = 'weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)
print("The confusion matrix:\n",cm)
print(clf_report)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~

The f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9916844900066377
The confusion matrix:
 [[45  0]
 [ 1 74]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

